version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: document_library_nginx
    volumes:
       - ./html:/usr/share/nginx/html:ro
#      - ./nginx.conf:/etc/nginx/nginx.conf

    restart: always
    ports:
      - 8012:80

