version: '2'
services:
  solr:
    image: solr
    ports:
     - "8011:8983"
    volumes:
      - ./mycores:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - wiki
volumes:
  data:
